name: Android CI/CD

on:
  push:
    branches: [ main ]
  workflow_dispatch:  # Allow manual triggering

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        fetch-depth: 0  # Needed for changelog generation

    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: 17

    - name: Grant execute permission for gradlew
      run: chmod +x ./gradlew

    - name: Build with Gradle
      run: ./gradlew build

    - name: Run unit tests
      run: ./gradlew test

    - name: Run Lint
      run: ./gradlew lint

    - name: Build Release APK
      run: ./gradlew assembleRelease

    - name: Prepare APKs
      run: |
        mkdir -p release-apks
        
        # Find and copy release APKs
        find app/build/outputs/apk/release -name '*.apk' ! -name '*debug*' ! -name '*unsigned*' -exec cp {} release-apks/ \;
        
        # Get version from Gradle
        VERSION=$(grep 'versionName' app/build.gradle.kts | sed -E 's/.*versionName.*=.*"(.*)".*/\1/')
        [ -z "$VERSION" ] && VERSION="1.0.0"
        
        # Rename APKs with version
        for f in release-apks/*.apk; do
          mv "$f" "release-apks/MiniMap-v${VERSION}.apk"
        done
        
        echo "VERSION=${VERSION}" >> $GITHUB_ENV

    - name: Upload Release APK
      uses: actions/upload-artifact@v4
      with:
        name: app-release
        path: release-apks/*.apk

  deploy:
    needs: build
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    
    steps:
    - name: Download artifact
      uses: actions/download-artifact@v4
      with:
        name: app-release
        path: apk-files/

    - name: Verify APK exists
      run: |
        if [ $(ls apk-files/ | wc -l) -eq 0 ]; then
          echo "Error: No APK files found!"
          exit 1
        fi

    - name: Generate Changelog
      id: changelog
      run: |
        # Get previous tag
        PREVIOUS_TAG=$(git describe --tags --abbrev=0 2>/dev/null || echo "")
        
        # Generate changelog from commits since last tag
        if [ -z "$PREVIOUS_TAG" ]; then
          CHANGES=$(git log --pretty=format:"- %s (%h)")
          echo "CHANGELOG=${CHANGES}" >> $GITHUB_OUTPUT
        else
          CHANGES=$(git log --pretty=format:"- %s (%h)" ${PREVIOUS_TAG}..HEAD)
          echo "CHANGELOG=${CHANGES}" >> $GITHUB_OUTPUT
        fi

    - name: Create Release
      uses: softprops/action-gh-release@v1
      with:
        tag_name: v${{ env.VERSION }}
        name: MiniMap v${{ env.VERSION }}
        body: |
          ### Changes
          ${{ steps.changelog.outputs.CHANGELOG }}
          
          ### Assets
          - APK file
          - ProGuard mapping file
        draft: false
        prerelease: false
        files: |
          apk-files/*.apk
          app/build/outputs/mapping/release/mapping.txt
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
