name: Android CI/CD

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: 17

    - name: Grant execute permission for gradlew
      run: chmod +x ./gradlew

    - name: Build with Gradle
      run: ./gradlew build

    - name: Run unit tests
      run: ./gradlew test

    - name: Run Lint
      run: ./gradlew lint

    - name: Build Release APK
      run: ./gradlew assembleRelease

    - name: Rename APK
      run: |
        mkdir -p renamed-apks
        for f in app/build/outputs/apk/release/*.apk; do
          cp "$f" "renamed-apks/MiniMap-v$(grep 'versionName' app/build.gradle.kts | sed -E 's/.*versionName.*=.*"(.*)".*/\1/').apk"
        done
        
    # Only one artifact
    - name: Upload Release APK
      uses: actions/upload-artifact@v4
      with:
        name: app-release
        path: |
          app/build/outputs/apk/release/*.apk
          !app/build/outputs/apk/debug/*.apk

  deploy:
    needs: build
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    
    steps:
    - name: Download artifact
      uses: actions/download-artifact@v4
      with:
        name: app-release
        path: apk-files/

    - name: Verify APK exists
      run: |
        echo "APK files:"
        ls -la apk-files/
        [ ! -f apk-files/*.apk ] && echo "Error: No APK found!" && exit 1

    - name: Get version from Gradle
      id: version
      run: |
        VERSION=$(grep 'versionName' app/build.gradle.kts | sed -E 's/.*versionName.*=.*"(.*)".*/\1/')
        [ -z "$VERSION" ] && VERSION="1.0"
        echo "VERSION=${VERSION}" >> $GITHUB_OUTPUT

    - name: Create Release
      uses: softprops/action-gh-release@v1
      with:
        tag_name: v${{ steps.version.outputs.VERSION }}
        name: MiniMap v${{ steps.version.outputs.VERSION }}
        generate_release_notes: true
        files: |
          apk-files/*.apk
          app/build/outputs/mapping/release/mapping.txt
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
