name: Android CI/CD

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: 17

    - name: Grant execute permission for gradlew
      run: chmod +x ./gradlew

    - name: Build with Gradle
      run: ./gradlew build

    - name: Run unit tests
      run: ./gradlew test

    - name: Run Lint
      run: ./gradlew lint

    - name: Debug APK files
      run: ls -la apk-files/

    - name: Build Release APK
      run: ./gradlew assembleRelease
        
    - name: Find and Upload APK
      uses: actions/upload-artifact@v4
      with:
        name: app-release
        path: |
          app/build/outputs/apk/**/*release*.apk
          app/build/outputs/apk/**/*-unsigned.apk

  deploy:
    needs: build
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    
    steps:
    - name: Download artifact
      uses: actions/download-artifact@v4
      with:
        name: app-release
        path: apk-files/

    - name: Get version from Gradle
      id: version
      run: |
        VERSION=$(grep 'versionName' app/build.gradle.kts | awk -F\" '{print $2}')
        echo "VERSION=${VERSION}" >> $GITHUB_OUTPUT
        echo "Using version: ${VERSION}"
    
    - name: Create Release
      uses: softprops/action-gh-release@v1
      with:
        tag_name: v${{ steps.version.outputs.VERSION || github.run_number }}
        name: Release v${{ steps.version.outputs.VERSION || github.run_number }}
        generate_release_notes: true
        files: apk-files/*.apk
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
